server:
  port: 8080

spring:
  application:
    name: 'Eureka Cloud Administration'
  boot:
    admin:
      context-path: '/admin'
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,hystrix.stream